"""
exam_seating.py
===============
Parses FAST NUCES Seating Plan PDF and stores/queries data in PostgreSQL.

PDF Structure per student (3 students per page):
    <Student Name>
    <Roll No>            e.g. 24K-0030
    Photo
    Code Course Name Day Time Teacher Seat
    <Course Name> <Teacher Name>          ← same line, teacher = last N capitalized words
    <CourseCode,Section> <Date> <Time> <Room Seat>
    ...repeated for each course...

Usage:
    from app.services.exam_seating import replace_exam_seating_from_pdf, get_seating_by_roll, format_seating_response
"""

import re
from typing import List, Dict, Optional
from sqlalchemy.orm import Session


# ─── PATTERNS ─────────────────────────────────────────────────────────────────

ROLL_NO_RE   = re.compile(r"^\d{2}[A-Za-z]-\d{4}$")
CODE_SEC_RE  = re.compile(r"^([A-Z]{2,6}\d{4}),([A-Z]{2,5}-\d+[A-Z]?)$")
DATE_RE      = re.compile(r"^\d{2}-[A-Za-z]{3}-\d{2,4}$")
TIME_RE      = re.compile(r"^\d{1,2}:\d{2}-\d{1,2}:\d{2}$")

SKIP_LINES = {
    "Final Examination Spring 2026",
    "examination department",
    "fast-nuces, karachi campus",
    "photo",
    "code course name day time teacher seat",
    "generated by m taha",
}

# Known multi-word teacher name prefixes to help split course vs teacher
TEACHER_PREFIXES = {"syed", "muhammad", "dr", "mr", "ms", "hafiz", "rana", "ch"}


# ─── HELPERS ──────────────────────────────────────────────────────────────────

def _clean_lines(raw: str) -> List[str]:
    lines = []
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.lower() in SKIP_LINES:
            continue
        if re.match(r"^page \d+ of \d+$", line.lower()):
            continue
        lines.append(line)
    return lines


def _split_course_teacher(line: str) -> tuple:
    """
    Split a line like:
        'Software Design and Analysis Syed Ahmed Khan'
        'Digital Forensics Waseem'
        'Operating Systems Rabia Ahmed'

    Strategy: words from the right that start with capital letter
    AND are NOT common English course words → teacher name.
    Course words (like 'Systems', 'Analysis') are tricky, so we use
    a minimum 1-word teacher and walk backwards until we hit a
    lowercase connector word or course keyword.
    """
    COURSE_WORDS = {
        "systems", "system", "analysis", "design", "management", "studies",
        "mathematics", "calculus", "statistics", "fundamentals", "principles",
        "introduction", "programming", "engineering", "networks", "network",
        "database", "databases", "structures", "structure", "algorithms",
        "algorithm", "intelligence", "artificial", "security", "computing",
        "communication", "communications", "human", "resources", "law",
        "research", "mining", "institutions", "markets", "project",
        "software", "hardware", "digital", "forensics", "operating",
        "probability", "multivariable", "discrete", "linear", "web",
        "business", "financial", "pakistan", "islamic", "english",
        "physics", "chemistry", "biology", "ethics", "logic",
    }

    words = line.split()
    if not words:
        return "", ""

    # Walk from right, collect teacher name words
    teacher_words = []
    split_at = len(words)

    for i in range(len(words) - 1, -1, -1):
        w = words[i]
        wl = w.lower()

        # Stop if we reach a lowercase word (connector/preposition)
        if w[0].islower():
            split_at = i + 1
            break

        # Stop if it's a known course keyword (unless it's part of teacher prefix)
        if wl in COURSE_WORDS and wl not in TEACHER_PREFIXES:
            if teacher_words:  # already have some teacher words, stop here
                split_at = i + 1
                break
            # No teacher words yet — take this as last resort (single-name teacher)
            teacher_words.insert(0, w)
            split_at = i
            break

        teacher_words.insert(0, w)
        split_at = i

        # Limit teacher name to 4 words max
        if len(teacher_words) >= 4:
            split_at = i
            break

    course_name = " ".join(words[:split_at]).strip()
    teacher     = " ".join(teacher_words).strip()

    # Sanity: if course_name is empty, the whole thing is teacher (unlikely)
    if not course_name:
        return line, ""

    return course_name, teacher


def _parse_data_line(line: str) -> Optional[Dict]:
    """
    Parse:  CS2006,BCS-4F 09-Apr-26 08:30-09:30 AB2RoomB 11
    Returns dict with code, section, day, time, seat or None.
    """
    parts = line.split()
    code_sec = None
    day_s = time_s = ""
    seat_parts = []
    past_time = False

    for tok in parts:
        if CODE_SEC_RE.match(tok):
            m = CODE_SEC_RE.match(tok)
            code_sec = (m.group(1), m.group(2))
        elif DATE_RE.match(tok):
            day_s = tok
        elif TIME_RE.match(tok):
            time_s = tok
            past_time = True
        elif past_time:
            seat_parts.append(tok)

    if not code_sec or not day_s or not time_s:
        return None

    return {
        "course_code": code_sec[0],
        "section":     code_sec[1],
        "day":         day_s,
        "time":        time_s,
        "seat":        " ".join(seat_parts),
    }


# ─── MAIN PARSER ──────────────────────────────────────────────────────────────

class SeatingRecord:
    __slots__ = [
        "student_name", "roll_no", "course_code", "section",
        "course_name", "day", "time", "teacher", "seat",
        "exam_session", "campus",
    ]
    def __init__(self, **kw):
        for k, v in kw.items():
            setattr(self, k, v)
    def __repr__(self):
        return f"SeatingRecord({self.roll_no}|{self.course_code}|{self.day}|{self.seat})"


def parse_pdf(
    pdf_path: str,
    exam_session: str = "Student Seating Plan Final Examination Spring 2026",
    campus: str = "Karachi",
) -> List[SeatingRecord]:
    """Parse entire PDF. Returns list of SeatingRecord."""
    import pdfplumber

    records: List[SeatingRecord] = []

    with pdfplumber.open(pdf_path) as pdf:
        total = len(pdf.pages)
        print(f"  [Seating] Parsing {total} pages …")

        for page_num, page in enumerate(pdf.pages):
            raw = page.extract_text()
            if not raw:
                continue

            lines = _clean_lines(raw)
            i = 0

            while i < len(lines):
                # Detect roll number
                if ROLL_NO_RE.match(lines[i]):
                    roll_no      = lines[i]
                    student_name = lines[i - 1] if i > 0 else "Unknown"

                    # Collect course blocks
                    j = i + 1
                    while j < len(lines):
                        if ROLL_NO_RE.match(lines[j]):
                            break  # next student

                        # Look for a data line (has CODE,SECTION date time seat)
                        data = _parse_data_line(lines[j])
                        if data:
                            # Course+teacher line is the line BEFORE this data line
                            course_line = lines[j - 1] if j > 0 else ""
                            # Don't use roll_no or student_name as course line
                            if ROLL_NO_RE.match(course_line) or course_line == student_name:
                                course_line = ""

                            course_name, teacher = _split_course_teacher(course_line)

                            records.append(SeatingRecord(
                                student_name = student_name,
                                roll_no      = roll_no,
                                course_code  = data["course_code"],
                                section      = data["section"],
                                course_name  = course_name,
                                day          = data["day"],
                                time         = data["time"],
                                teacher      = teacher,
                                seat         = data["seat"],
                                exam_session = exam_session,
                                campus       = campus,
                            ))

                        j += 1

                    i = j
                else:
                    i += 1

            if (page_num + 1) % 200 == 0:
                print(f"  [Seating] {page_num+1}/{total} pages, {len(records)} records …")

    print(f"  [Seating] ✅ Parsing done — {len(records)} records")
    return records


# ─── DB OPERATIONS ────────────────────────────────────────────────────────────

def replace_exam_seating_from_pdf(
    session: Session,
    pdf_path: str,
    session_name: str = "Final Examination Seating Plan Spring 2026",
    campus: str = "Karachi",
    replace_all: bool = False,
) -> int:
    """
    Parse PDF and replace DB records for this exam session + campus.
    Called from main.py /exam/import in a background thread.
    Returns number of rows inserted.
    """
    from database.models import ExamSeating

    records = parse_pdf(pdf_path, session_name, campus)

    # Delete stale records
    if replace_all:
        print("  [Seating] Deleting all old records …")
        session.query(ExamSeating).delete(synchronize_session=False)
    else:
        print(f"  [Seating] Deleting old records for '{session_name}' …")
        session.query(ExamSeating).filter(
            ExamSeating.exam_session == session_name,
            ExamSeating.campus       == campus,
        ).delete(synchronize_session=False)
    session.flush()

    # Bulk insert in batches
    print(f"  [Seating] Inserting {len(records)} rows …")
    batch_size = 500
    db_rows = [
        ExamSeating(
            student_name = r.student_name,
            roll_no      = r.roll_no,
            course_code  = r.course_code,
            section      = r.section,
            course_name  = r.course_name,
            day          = r.day,
            time         = r.time,
            teacher      = r.teacher,
            seat         = r.seat,
            exam_session = r.exam_session,
            campus       = r.campus,
        )
        for r in records
    ]
    for start in range(0, len(db_rows), batch_size):
        session.bulk_save_objects(db_rows[start : start + batch_size])
        session.flush()

    session.commit()
    print(f"  [Seating] ✅ {len(db_rows)} rows committed.")
    return len(db_rows)


# ─── QUERY HELPER (used by chatbot) ───────────────────────────────────────────

def get_seating_by_roll(
    session: Session,
    roll_no: str,
    exam_session: Optional[str] = None,
) -> List[Dict]:
    from database.models import ExamSeating

    q = session.query(ExamSeating).filter(
        ExamSeating.roll_no.ilike(roll_no.strip())
    )
    if exam_session:
        q = q.filter(ExamSeating.exam_session == exam_session)

    rows = q.order_by(ExamSeating.day, ExamSeating.time).all()
    return [
        {
            "roll_no":      r.roll_no,
            "name":         r.student_name,
            "course_code":  r.course_code,
            "course_name":  r.course_name,
            "section":      r.section,
            "day":          r.day,
            "time":         r.time,
            "teacher":      r.teacher,
            "seat":         r.seat,
            "exam_session": r.exam_session,
            "campus":       r.campus,
        }
        for r in rows
    ]


def format_seating_response(records: List[Dict], language_hint: str = "english") -> str:
    """Format seating records into a clean chatbot reply."""
    if not records:
        if language_hint == "roman_urdu":
            return (
                "Is roll number ka koi seating plan nahi mila. "
                "Roll number dobara check karein."
            )
        return (
            "No seating plan found for this roll number. "
            "Please verify your roll number and try again."
        )

    name         = records[0]["name"]
    roll_no      = records[0]["roll_no"]
    exam_session = records[0]["exam_session"]

    if language_hint == "roman_urdu":
        header = f"**{name}** ({roll_no}) ka **{exam_session}** seating plan:\n"
    else:
        header = f"**{name}** ({roll_no}) — **{exam_session}** Seating Plan:\n"

    lines = [header]
    for i, r in enumerate(records, 1):
        lines.append(
            f"{i}. **{r['course_name']}** `{r['course_code']}`\n"
            f"   📅 {r['day']}  🕐 {r['time']}\n"
            f"   👨‍🏫 {r['teacher']}\n"
            f"   🪑 **Seat: {r['seat']}**\n"
        )

    return "\n".join(lines)


# ─── STANDALONE TEST ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    pdf = sys.argv[1] if len(sys.argv) > 1 else "Student Seating Plan Final Examination Spring 2026"
    recs = parse_pdf(pdf)
    print(f"\nTotal records: {len(recs)}")
    print("\nSample (first 5):")
    for r in recs[:5]:
        print(f"  {r.student_name} ({r.roll_no}) | {r.course_name} | {r.teacher} | {r.day} {r.time} | {r.seat}")