"""
exam_seating.py
===============
Parses FAST NUCES Seating Plan PDF and stores/queries data in PostgreSQL.

PDF Structure per student (3 students per page):
    <Student Name>
    <Roll No>            e.g. 24K-0030
    Photo
    Code Course Name Day Time Teacher Seat
    <Course Name> <Teacher Name>          ← same line, teacher = last N capitalized words
    <CourseCode,Section> <Date> <Time> <Room Seat>
    ...repeated for each course...

Usage:
    from app.services.exam_seating import replace_exam_seating_from_pdf, get_seating_by_roll, format_seating_response
"""

import re
from typing import List, Dict, Optional
from sqlalchemy.orm import Session


# ─── PATTERNS ─────────────────────────────────────────────────────────────────

ROLL_NO_RE   = re.compile(r"^\d{2}[A-Za-z]-\d{4}$")
CODE_SEC_RE  = re.compile(r"^([A-Z]{2,6}\d{4}),([A-Z]{2,5}-\d+[A-Z]?)$")
DATE_RE      = re.compile(r"^\d{2}-[A-Za-z]{3}-\d{2,4}$")
TIME_RE      = re.compile(r"^\d{1,2}:\d{2}-\d{1,2}:\d{2}$")

SKIP_LINES = {
    "Final Examination Spring 2026",
    "examination department",
    "fast-nuces, karachi campus",
    "photo",
    "code course name day time teacher seat",
    "generated by m taha",
}

# Known multi-word teacher name prefixes to help split course vs teacher
TEACHER_PREFIXES = {"syed", "muhammad", "dr", "mr", "ms", "hafiz", "rana", "ch"}


# ─── HELPERS ──────────────────────────────────────────────────────────────────

def _clean_lines(raw: str) -> List[str]:
    lines = []
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.lower() in SKIP_LINES:
            continue
        if re.match(r"^page \d+ of \d+$", line.lower()):
            continue
        lines.append(line)
    return lines


def _split_course_teacher(line: str) -> tuple:
    """
    Split a line like:
        'Software Design and Analysis Syed Ahmed Khan'
        'Digital Forensics Waseem'
        'Operating Systems Rabia Ahmed'

    Strategy: words from the right that start with capital letter
    AND are NOT common English course words → teacher name.
    Course words (like 'Systems', 'Analysis') are tricky, so we use
    a minimum 1-word teacher and walk backwards until we hit a
    lowercase connector word or course keyword.
    """
    COURSE_WORDS = {
        "systems", "system", "analysis", "design", "management", "studies",
        "mathematics", "calculus", "statistics", "fundamentals", "principles",
        "introduction", "programming", "engineering", "networks", "network",
        "database", "databases", "structures", "structure", "algorithms",
        "algorithm", "intelligence", "artificial", "security", "computing",
        "communication", "communications", "human", "resources", "law",
        "research", "mining", "institutions", "markets", "project",
        "software", "hardware", "digital", "forensics", "operating",
        "probability", "multivariable", "discrete", "linear", "web",
        "business", "financial", "pakistan", "islamic", "english",
        "physics", "chemistry", "biology", "ethics", "logic",
    }

    words = line.split()
    if not words:
        return "", ""

    # Walk from right, collect teacher name words
    teacher_words = []
    split_at = len(words)

    for i in range(len(words) - 1, -1, -1):
        w = words[i]
        wl = w.lower()

        # Stop if we reach a lowercase word (connector/preposition)
        if w[0].islower():
            split_at = i + 1
            break

        # Stop if it's a known course keyword (unless it's part of teacher prefix)
        if wl in COURSE_WORDS and wl not in TEACHER_PREFIXES:
            if teacher_words:  # already have some teacher words, stop here
                split_at = i + 1
                break
            # No teacher words yet — take this as last resort (single-name teacher)
            teacher_words.insert(0, w)
            split_at = i
            break

        teacher_words.insert(0, w)
        split_at = i

        # Limit teacher name to 4 words max
        if len(teacher_words) >= 4:
            split_at = i
            break

    course_name = " ".join(words[:split_at]).strip()
    teacher     = " ".join(teacher_words).strip()

    # Sanity: if course_name is empty, the whole thing is teacher (unlikely)
    if not course_name:
        return line, ""

    return course_name, teacher


def _parse_data_line(line: str) -> Optional[Dict]:
    """
    Parse:  CS2006,BCS-4F 09-Apr-26 08:30-09:30 AB2RoomB 11
    Returns dict with code, section, day, time, seat or None.
    """
    parts = line.split()
    code_sec = None
    day_s = time_s = ""
    seat_parts = []
    past_time = False

    for tok in parts:
        if CODE_SEC_RE.match(tok):
            m = CODE_SEC_RE.match(tok)
            code_sec = (m.group(1), m.group(2))
        elif DATE_RE.match(tok):
            day_s = tok
        elif TIME_RE.match(tok):
            time_s = tok
            past_time = True
        elif past_time:
            seat_parts.append(tok)

    if not code_sec or not day_s or not time_s:
        return None

    return {
        "course_code": code_sec[0],
        "section":     code_sec[1],
        "day":         day_s,
        "time":        time_s,
        "seat":        " ".join(seat_parts),
    }


# ─── MAIN PARSER ──────────────────────────────────────────────────────────────

class SeatingRecord:
    __slots__ = [
        "student_name", "roll_no", "course_code", "section",
        "course_name", "day", "time", "teacher", "seat",
        "exam_session", "campus",
    ]
    def __init__(self, **kw):
        for k, v in kw.items():
            setattr(self, k, v)
    def __repr__(self):
        return f"SeatingRecord({self.roll_no}|{self.course_code}|{self.day}|{self.seat})"


def parse_pdf(
    pdf_path: str,
    exam_session: str = "Student Seating Plan Final Examination Spring 2026",
    campus: str = "Karachi",
) -> List[SeatingRecord]:
    """Parse entire PDF. Returns list of SeatingRecord."""
    import pdfplumber

    records: List[SeatingRecord] = []

    with pdfplumber.open(pdf_path) as pdf:
        total = len(pdf.pages)
        print(f"  [Seating] Parsing {total} pages …")

        for page_num, page in enumerate(pdf.pages):
            raw = page.extract_text()
            if not raw:
                continue

            lines = _clean_lines(raw)
            i = 0

            while i < len(lines):
                # Detect roll number
                if ROLL_NO_RE.match(lines[i]):
                    roll_no      = lines[i]
                    student_name = lines[i - 1] if i > 0 else "Unknown"

                    # Collect course blocks
                    j = i + 1
                    while j < len(lines):
                        if ROLL_NO_RE.match(lines[j]):
                            break  # next student

                        # Look for a data line (has CODE,SECTION date time seat)
                        data = _parse_data_line(lines[j])
                        if data:
                            # Course+teacher line is the line BEFORE this data line
                            course_line = lines[j - 1] if j > 0 else ""
                            # Don't use roll_no or student_name as course line
                            if ROLL_NO_RE.match(course_line) or course_line == student_name:
                                course_line = ""

                            course_name, teacher = _split_course_teacher(course_line)

                            records.append(SeatingRecord(
                                student_name = student_name,
                                roll_no      = roll_no,
                                course_code  = data["course_code"],
                                section      = data["section"],
                                course_name  = course_name,
                                day          = data["day"],
                                time         = data["time"],
                                teacher      = teacher,
                                seat         = data["seat"],
                                exam_session = exam_session,
                                campus       = campus,
                            ))

                        j += 1

                    i = j
                else:
                    i += 1

            if (page_num + 1) % 200 == 0:
                print(f"  [Seating] {page_num+1}/{total} pages, {len(records)} records …")

    print(f"  [Seating] ✅ Parsing done — {len(records)} records")
    return records


# ─── DB OPERATIONS ────────────────────────────────────────────────────────────

def replace_exam_seating_from_pdf(
    session: Session,
    pdf_path: str,
    session_name: str = "Final Examination Seating Plan Spring 2026",
    campus: str = "Karachi",
    replace_all: bool = False,
) -> int:
    """
    Parse PDF and replace DB records for this exam session + campus.
    Called from main.py /exam/import in a background thread.
    Returns number of rows inserted.
    """
    from database.models import ExamSeating

    records = parse_pdf(pdf_path, session_name, campus)

    # Delete stale records
    if replace_all:
        print("  [Seating] Deleting all old records …")
        session.query(ExamSeating).delete(synchronize_session=False)
    else:
        print(f"  [Seating] Deleting old records for '{session_name}' …")
        session.query(ExamSeating).filter(
            ExamSeating.exam_session == session_name,
            ExamSeating.campus       == campus,
        ).delete(synchronize_session=False)
    session.flush()

    # Bulk insert in batches
    print(f"  [Seating] Inserting {len(records)} rows …")
    batch_size = 500
    db_rows = [
        ExamSeating(
            student_name = r.student_name,
            roll_no      = r.roll_no,
            course_code  = r.course_code,
            section      = r.section,
            course_name  = r.course_name,
            day          = r.day,
            time         = r.time,
            teacher      = r.teacher,
            seat         = r.seat,
            exam_session = r.exam_session,
            campus       = r.campus,
        )
        for r in records
    ]
    for start in range(0, len(db_rows), batch_size):
        session.bulk_save_objects(db_rows[start : start + batch_size])
        session.flush()

    session.commit()
    print(f"  [Seating] ✅ {len(db_rows)} rows committed.")
    return len(db_rows)


# ─── QUERY HELPER (used by chatbot) ───────────────────────────────────────────

def get_seating_by_roll(
    session: Session,
    roll_no: str,
    exam_session: Optional[str] = None,
) -> List[Dict]:
    from database.models import ExamSeating

    q = session.query(ExamSeating).filter(
        ExamSeating.roll_no.ilike(roll_no.strip())
    )
    if exam_session:
        q = q.filter(ExamSeating.exam_session == exam_session)

    rows = q.order_by(ExamSeating.day, ExamSeating.time).all()
    return [
        {
            "roll_no":      r.roll_no,
            "name":         r.student_name,
            "course_code":  r.course_code,
            "course_name":  r.course_name,
            "section":      r.section,
            "day":          r.day,
            "time":         r.time,
            "teacher":      r.teacher,
            "seat":         r.seat,
            "exam_session": r.exam_session,
            "campus":       r.campus,
        }
        for r in rows
    ]


def format_seating_response(records: List[Dict], language_hint: str = "english") -> str:
    """Format seating records into a clean chatbot reply."""
    if not records:
        if language_hint == "roman_urdu":
            return (
                "Is roll number ka koi seating plan nahi mila. "
                "Roll number dobara check karein."
            )
        return (
            "No seating plan found for this roll number. "
            "Please verify your roll number and try again."
        )

    name         = records[0]["name"]
    roll_no      = records[0]["roll_no"]
    exam_session = records[0]["exam_session"]

    if language_hint == "roman_urdu":
        header = f"**{name}** ({roll_no}) ka **{exam_session}** seating plan:\n"
    else:
        header = f"**{name}** ({roll_no}) — **{exam_session}** Seating Plan:\n"

    lines = [header]
    for i, r in enumerate(records, 1):
        lines.append(
            f"{i}. **{r['course_name']}** `{r['course_code']}`\n"
            f"   📅 {r['day']}  🕐 {r['time']}\n"
            f"   👨‍🏫 {r['teacher']}\n"
            f"   🪑 **Seat: {r['seat']}**\n"
        )

    return "\n".join(lines)


# ─── TIMETABLE PDF PARSER ─────────────────────────────────────────────────────
# Same pattern as seating plan: parse PDF → list of records → bulk insert to DB.
# PDF format: 1 page per section, table with Day + 9 time-slot columns.
# Each cell: "Subject\n(Teacher)\n@ Room" or empty/None for merged labs.

_TT_TEACHER_RE = re.compile(r'\(([^)]+)\)')
_TT_ROOM_RE    = re.compile(r'@\s*(.+?)$')


def _normalize_time_slot(slot: str) -> str:
    """Normalize PDF time slot to DB format.
    '8:00-8:50'   → '08:00-08:50'
    '9:50:-10:40' → '09:50-10:40'  (fix typo colon)
    '12:35-1:25'  → '12:35-01:25'
    """
    slot = re.sub(r':(?=-)', '', slot)  # remove colon directly before dash
    match = re.match(r'(\d{1,2}):(\d{2})\s*-\s*(\d{1,2}):(\d{2})', slot.strip())
    if match:
        h1, m1, h2, m2 = match.groups()
        return f"{int(h1):02d}:{m1}-{int(h2):02d}:{m2}"
    return slot.strip()


def _parse_timetable_cell(cell_text: str) -> Optional[Dict]:
    """Parse a timetable cell like 'Subject\\n(Teacher)\\n@ Room'.
    Returns dict with subject, teacher, room or None.
    Handles cells with multiple parentheses (e.g. 'Understanding Sirat-Un-Nabi (PBUH) (Teacher) @ Room').
    """
    if not cell_text or not cell_text.strip():
        return None

    # Join multiline text for easier parsing
    text = cell_text.replace('\n', ' ')
    text = re.sub(r'\s+', ' ', text).strip()

    # Extract room (text after @)
    room = ""
    room_match = _TT_ROOM_RE.search(text)
    if room_match:
        room = room_match.group(1).strip()
        before_room = text[:room_match.start()].strip()
    else:
        before_room = text

    # Teacher is in the last parentheses before @ Room
    paren_matches = list(re.finditer(r'\(([^)]+)\)', before_room))
    if paren_matches:
        last_paren = paren_matches[-1]
        teacher = last_paren.group(1).strip()
        subject = before_room[:last_paren.start()].strip()
    else:
        teacher = ""
        subject = before_room

    subject = re.sub(r'\s+', ' ', subject).strip()
    if not subject:
        return None

    return {"subject": subject, "teacher": teacher, "room": room}


class TimetableRecord:
    """Lightweight container for one parsed timetable row."""
    __slots__ = [
        "section", "day", "time", "subject",
        "teacher_name", "room_number", "campus",
    ]
    def __init__(self, **kw):
        for k, v in kw.items():
            setattr(self, k, v)
    def __repr__(self):
        return (f"TimetableRecord({self.section}|{self.day}|"
                f"{self.time}|{self.subject}|{self.teacher_name})")


def parse_timetable_pdf(
    pdf_path: str,
    campus: str = "Karachi",
) -> List[TimetableRecord]:
    """Parse timetable PDF. Returns list of TimetableRecord.

    PDF structure:
        - Each page belongs to a section (e.g. 'Timetable for Section: BAI-1A')
        - Large sections (e.g. 7th sem electives) may spill across multiple pages
        - Table header has Day + 9 time-slot columns
        - Rows have day name; multi-row elective blocks inherit the day
        - Cells contain 'Subject\\n(Teacher)\\n@ Room', None for merged lab slots
    """
    import pdfplumber

    records: List[TimetableRecord] = []
    current_section = ""

    with pdfplumber.open(pdf_path) as pdf:
        total = len(pdf.pages)
        print(f"  [Timetable] Parsing {total} pages ...")

        for page_num, page in enumerate(pdf.pages):
            text = page.extract_text()
            if not text:
                continue

            # ── Section name from title (or inherit if continuation page) ──
            section_match = re.search(
                r'Timetable\s+for\s+Section:\s*(\S+)', text, re.IGNORECASE,
            )
            if section_match:
                current_section = section_match.group(1).strip()
            elif not current_section:
                continue
            section = current_section

            # ── Extract table ──
            tables = page.extract_tables()
            if not tables:
                continue
            table = tables[0]
            if len(table) < 2:
                continue

            # Header: ['Day', '8:00-8:50', '8:55-9:45', ...]
            header = table[0]
            time_slots = [
                _normalize_time_slot(h) for h in header[1:] if h
            ]

            # ── Data rows (Mon–Sat) ──
            current_day = ""
            for row in table[1:]:
                if not row:
                    continue
                day_raw = row[0].strip() if row[0] else ""
                if day_raw:
                    current_day = day_raw
                elif not current_day:
                    continue
                day = current_day

                current_spanning = None  # tracks merged-cell (lab) data

                for col_idx, cell in enumerate(row[1:]):
                    if col_idx >= len(time_slots):
                        break
                    time_slot = time_slots[col_idx]

                    if cell is None:
                        # Merged cell — lab spanning multiple slots
                        if current_spanning:
                            records.append(TimetableRecord(
                                section=section,
                                day=day,
                                time=time_slot,
                                subject=current_spanning["subject"],
                                teacher_name=current_spanning["teacher"],
                                room_number=current_spanning["room"],
                                campus=campus,
                            ))
                    elif cell.strip():
                        parsed = _parse_timetable_cell(cell)
                        if parsed:
                            records.append(TimetableRecord(
                                section=section,
                                day=day,
                                time=time_slot,
                                subject=parsed["subject"],
                                teacher_name=parsed["teacher"],
                                room_number=parsed["room"],
                                campus=campus,
                            ))
                            current_spanning = parsed
                        else:
                            current_spanning = None
                    else:
                        # Empty string — genuinely free slot
                        current_spanning = None

            if (page_num + 1) % 20 == 0:
                print(f"  [Timetable] {page_num+1}/{total} pages, "
                      f"{len(records)} records ...")

    print(f"  [Timetable] ✅ Parsing done — {len(records)} records")
    return records


def replace_timetable_from_pdf(
    session,
    pdf_path: str,
    campus: str = "Karachi",
) -> int:
    """Parse timetable PDF and replace ALL timetable rows in DB.

    1. Parses the PDF into TimetableRecord list.
    2. Deletes every row from university_timetable.
    3. Bulk-inserts the new rows.
    Returns number of rows inserted.
    """
    from database.models import Timetable

    records = parse_timetable_pdf(pdf_path, campus)

    # ── Delete old timetable data ──
    print("  [Timetable] Deleting old timetable records ...")
    session.query(Timetable).delete(synchronize_session=False)
    session.flush()

    # ── Bulk insert ──
    print(f"  [Timetable] Inserting {len(records)} rows ...")
    batch_size = 500
    db_rows = [
        Timetable(
            section      = r.section,
            day          = r.day,
            time         = r.time,
            subject      = r.subject,
            teacher_name = r.teacher_name,
            room_number  = r.room_number,
            campus       = r.campus,
        )
        for r in records
    ]
    for start in range(0, len(db_rows), batch_size):
        session.bulk_save_objects(db_rows[start : start + batch_size])
        session.flush()

    session.commit()
    print(f"  [Timetable] ✅ {len(db_rows)} rows committed.")
    return len(db_rows)


# ─── STANDALONE TEST ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    pdf = sys.argv[1] if len(sys.argv) > 1 else "Student Seating Plan Final Examination Spring 2026"
    recs = parse_pdf(pdf)
    print(f"\nTotal records: {len(recs)}")
    print("\nSample (first 5):")
    for r in recs[:5]:
        print(f"  {r.student_name} ({r.roll_no}) | {r.course_name} | {r.teacher} | {r.day} {r.time} | {r.seat}")